# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CARL',
                'doc_host': 'https://clembergerot.github.io',
                'git_url': 'https://github.com/clembergerot/CARL',
                'lib_path': 'CARL'},
  'syms': {'CARL.core': {'CARL.core.foo': ('core.html#foo', 'CARL/core.py')}}}
